<?php
/**
 * Default TinyMCE language file
 *
 * @package tinymce
 * @language de
 */
$_lang['tiny.toggle_editor'] = 'Editor ein- und ausschalten: ';
$_lang['setting_tiny.base_url'] = 'TinyMCE Document Base URL';
$_lang['setting_tiny.base_url_desc'] = 'Allows the setting of a base URL property to override the document_base_url TinyMCE settings. Useful for rootrelative environments.';
$_lang['setting_tiny.convert_fonts_to_spans'] = 'Convert Fonts to Spans';
$_lang['setting_tiny.convert_fonts_to_spans_desc'] = 'If you set this option to true, TinyMCE will convert all font elements to span elements and generate span elements instead of font elements. This option should be used in order to get more W3C compatible code, since font elements are deprecated.';
$_lang['setting_tiny.convert_newlines_to_brs'] = 'Convert Newlines to BRs';
$_lang['setting_tiny.convert_newlines_to_brs_desc'] = 'If you set this option to true, newline characters codes get converted into br elements. This option is set to false by default.';
$_lang['setting_tiny.css_selectors'] = 'CSS-Selektoren';
$_lang['setting_tiny.css_selectors_desc'] = 'Hier können Sie eine Liste von Selektoren eingeben, die im Editor verfügbar sein sollen. Geben Sie sie folgendermaßen ein:<br />"angezeigterName=selektorName;angezeigterName2=selektorName2"<br />Wenn Sie zum Beispiel die Selektoren <b>.mono</b> und <b>.smallText</b> in Ihrer CSS-Datei haben, können Sie sie hier so hinzufügen:<br />"Monospace-Text=mono;Kleiner Text=smallText"<br />Beachten Sie, dass hinter dem letzten Eintrag kein Semikolon stehen sollte.';
$_lang['setting_tiny.custom_buttons1'] = 'Selbstdefinierte Button-Zeile 1';
$_lang['setting_tiny.custom_buttons1_desc'] = 'Geben Sie die für die erste Zeile zu verwendenden Buttons als kommaseparierte Liste ein. Stellen Sie sicher, dass für jeden Button das benötigte Plugin in der Einstellung "Zu verwendende Plugins" aktiviert ist.';
$_lang['setting_tiny.custom_buttons2'] = 'Selbstdefinierte Button-Zeile 2';
$_lang['setting_tiny.custom_buttons2_desc'] = 'Geben Sie die für die zweite Zeile zu verwendenden Buttons als kommaseparierte Liste ein. Stellen Sie sicher, dass für jeden Button das benötigte Plugin in der Einstellung "Zu verwendende Plugins" aktiviert ist.';
$_lang['setting_tiny.custom_buttons3'] = 'Selbstdefinierte Button-Zeile 3';
$_lang['setting_tiny.custom_buttons3_desc'] = 'Geben Sie die für die dritte Zeile zu verwendenden Buttons als kommaseparierte Liste ein. Stellen Sie sicher, dass für jeden Button das benötigte Plugin in der Einstellung "Zu verwendende Plugins" aktiviert ist.';
$_lang['setting_tiny.custom_buttons4'] = 'Selbstdefinierte Button-Zeile 4';
$_lang['setting_tiny.custom_buttons4_desc'] = 'Geben Sie die für die vierte Zeile zu verwendenden Buttons als kommaseparierte Liste ein. Stellen Sie sicher, dass für jeden Button das benötigte Plugin in der Einstellung "Zu verwendende Plugins" aktiviert ist.';
$_lang['setting_tiny.custom_buttons5'] = 'Selbstdefinierte Button-Zeile 5';
$_lang['setting_tiny.custom_buttons5_desc'] = 'Geben Sie die für die fünfte Zeile zu verwendenden Buttons als kommaseparierte Liste ein. Stellen Sie sicher, dass für jeden Button das benötigte Plugin in der Einstellung "Zu verwendende Plugins" aktiviert ist.';
$_lang['setting_tiny.custom_plugins'] = 'Zu verwendende Plugins';
$_lang['setting_tiny.custom_plugins_desc'] = 'Eine kommaseparierte Liste der zu verwendenden TinyMCE-Plugins.';
$_lang['setting_tiny.editor_theme'] = 'Editor-Theme';
$_lang['setting_tiny.element_format'] = 'Element Format';
$_lang['setting_tiny.element_format_desc'] = 'This option enables control if elements should be in html or xhtml mode. xhtml is the default state for this option. This means that for example <br /> will be <br> if you set this option to "html".';
$_lang['setting_tiny.entity_encoding'] = 'Entity Encoding';
$_lang['setting_tiny.entity_encoding_desc'] = 'This option controls how entities/characters get processed by TinyMCE. Available values are "named", "numeric" and "raw".';
$_lang['setting_tiny.fix_nesting'] = 'Auto-fix Nesting';
$_lang['setting_tiny.fix_nesting_desc'] = 'This option controls if invalid contents should be corrected before insertion in IE. IE has a bug that produced an invalid DOM tree if the input contents are not correct so this option tries to fix this using preprocessing of the HTML string. This option is disabled by default since it might be a bit slow.';
$_lang['setting_tiny.fix_table_elements'] = 'Auto-fix Table Elements';
$_lang['setting_tiny.fix_table_elements_desc'] = 'This option enables you to specify that table elements should be moved outside paragraphs or other block elements. If you enable this option block elements will be split into two chunks when a table is found within it. This option is disabled by default.';
$_lang['setting_tiny.font_size_classes'] = 'Font Size Classes';
$_lang['setting_tiny.font_size_classes_desc'] = 'This option allows specification of a comma separated list of class names that is to be used when the user selects font sizes. This option is only used when the convert_fonts_to_spans option is enabled. This list of classes should be 7 items. This option is not used by default, but can be useful if you want to have custom classes for each font size for browser compatibility.';
$_lang['setting_tiny.font_size_style_values'] = 'Font Size Style Values';
$_lang['setting_tiny.font_size_style_values_desc'] = 'This option allows specification of a comma separated list of style values that is to be used when the user selects font sizes. This option is only used when the convert_fonts_to_spans option is enabled. This list of style values should be 7 items. This option is not used by default, but can be useful if you want to have custom CSS values for each font size for browser compatibility. Defaults to: xx-small,x-small,small,medium,large,x-large,xx-large.';
$_lang['setting_tiny.forced_root_block'] = 'Forced Root Block';
$_lang['setting_tiny.forced_root_block_desc'] = 'This option enables you to make sure that any non block elements or text nodes are wrapped in block elements. For example <strong>something</strong> will result in output like: <p><strong>something</strong></p>.';
$_lang['setting_tiny.indentation'] = 'Indentation';
$_lang['setting_tiny.indentation_desc'] = 'This option allows specification of the indentation level for indent/outdent buttons in the UI. This defaults to 30px but can be any value.';
$_lang['setting_tiny.invalid_elements'] = 'Invalid Elements';
$_lang['setting_tiny.invalid_elements_desc'] = 'This option should contain a comma separated list of element names to exclude from the content. Elements in this list will be removed when TinyMCE executes a cleanup.';
$_lang['setting_tiny.nowrap'] = 'Prevent Editor Wrap';
$_lang['setting_tiny.nowrap_desc'] = 'This nowrap option enables you to control how whitespace is to be wordwrapped within the editor. This option is set to false by default, but if you enable it by setting it to true editor contents will never wrap.';
$_lang['setting_tiny.object_resizing'] = 'Objekt-Größenänderung im Editor';
$_lang['setting_tiny.object_resizing_desc'] = 'Diese Option gibt Ihnen die Möglichkeit, die Größenänderungs-Kontrollelemente von Tabellen und Bildern in Firefox/Mozilla ein- und auszuschalten. Standardmäßig sind diese eingeschaltet.';
$_lang['setting_tiny.remove_linebreaks'] = 'Remove Linebreaks';
$_lang['setting_tiny.remove_linebreaks_desc'] = 'This option controls whether line break characters should be removed from output HTML.';
$_lang['setting_tiny.remove_redundant_brs'] = 'Remove Redundant BRs';
$_lang['setting_tiny.remove_redundant_brs_desc'] = 'This option is enabled by default and will control the output of trailing BR elements at the end of block elements. Since IE cannot render these properly we need to remove them by default to ensure proper output across all browsers. So for some browsers this BR at the end of the LI at the example below is redundant.';
$_lang['setting_tiny.removeformat_selector'] = 'RemoveFormat Selector';
$_lang['setting_tiny.removeformat_selector_desc'] = 'This option allows specification of which elements should be removed when you press the removeformat button. This is a CSS selector pattern.';
$_lang['setting_tiny.path_options'] = 'Pfad-Optionen';
$_lang['setting_tiny.path_options_desc'] = 'Mögliche Werte: "rootrelative", "docrelative" oder "fullpathurl".';
$_lang['setting_tiny.table_inline_editing'] = 'Tabellen-Bearbeitung';
$_lang['setting_tiny.table_inline_editing_desc'] = 'Diese Option gibt Ihnen die Möglichkeit, die Kontrollelemente für die Inline-Bearbeitung von Tabellen in Firefox/Mozilla ein- und auszuschalten. Laut der TinyMCE-Dokumentation sind diese Kontrollelemente nicht ganz fehlerfrei und nicht änderbar, daher sind sie standardmäßig deaktiviert.';
$_lang['setting_tiny.template_list'] = 'Template-Liste';
$_lang['setting_tiny.template_list_desc'] = 'Geben Sie eine Liste von Templates für das Template-Plugin ein. Die Einträge müssen durch Kommata getrennt sein und das Format Name:URL:Beschreibung haben. Beispiel: MeinTemplate:assets/templates/mytemp.html:Mein eigenes Template';
$_lang['setting_tiny.template_list_snippet'] = 'Template List Snippet';
$_lang['setting_tiny.template_list_snippet_desc'] = 'Enter the name of a snippet that will generate a list of templates compatible with the tiny.template_list format (name:URL:description). If a snippet is named, the results returned by the snippet call will be used rather than any value present in tiny.template_list';
$_lang['setting_tiny.template_selected_content_classes'] = 'Template-CSS-Klassen für markierte Inhalte';
$_lang['setting_tiny.template_selected_content_classes_desc'] = 'Geben Sie eine Liste von CSS-Klassennamen für das Template-Plugin ein. Die Einträge müssen durch Leerzeichen getrennt sein. Der Inhalt jedes Vorlagen-Elements mit einer der angegebenen CSS-Klassen wird durch die im Editor markierten Inhalte ersetzt, wenn die Vorlage eingefügt wird.';
$_lang['setting_tiny.theme_advanced_blockformats'] = 'HTML-Blockelemente';
$_lang['setting_tiny.theme_advanced_blockformats_desc'] = 'Diese Einstellung sollte eine kommaseparierte Liste von HTML-Blockelementen enthalten, die in dem Drop-Down-Feld "Vorlage" angezeigt werden sollen. Diese Option ist nur verfügbar, wenn das Theme "advanced" verwendet wird. Mögliche Werte sind z. B.: p, h1, h2, h3, h4, h5, h6, div, blockquote, code, pre, address.';
$_lang['setting_tiny.theme_advanced_font_sizes'] = 'Advanced Theme Font Sizes';
$_lang['setting_tiny.theme_advanced_font_sizes_desc'] = 'This option should contain a comma separated list of font sizes to include. Each item in the list should be a valid value for the font-style CSS property (10px, 12pt, 1em, etc.). Example: Big text=30px,Small text=small,My Text Size=.mytextsize';
$_lang['setting_tiny.skin'] = 'TinyMCE-Skin';
$_lang['setting_tiny.skin_desc'] = 'Diese Einstellung ermöglicht es Ihnen, anzugeben, welchen Skin Sie mit Ihrem TinyMCE-Editor-Theme verwenden möchten. Ein Skin ist im Grunde eine CSS-Datei, die aus dem Skins-Verzeichnis in das Theme geladen wird. Das Theme "advanced", das mit TinyMCE ausgeliefert wird, hat zwei Skins; diese heißen "default" und "o2k7". Wir haben einen weiteren Skin namens "cirkuit" hinzugefügt, der standardmäßig vorausgewählt ist.';
$_lang['setting_tiny.skin_variant'] = 'TinyMCE-Skin-Variante';
$_lang['setting_tiny.skin_variant_desc'] = 'Einige Skins haben eine oder mehrere zusätzliche Varianten, die man auswählen kann. Der Skin "cirkuit" besitzt die zusätzliche Variante "silver", für den Skin "o2k7" stehen die zusätzlichen Varianten "black" und "silver" zur Verfügung. Standardmäßig ist diese Einstellung leer.';
$_lang['area_advanced-theme'] = 'Advanced Theme';
$_lang['area_cleanup-output'] = 'Cleanup/Output';
$_lang['area_custom-buttons'] = 'Custom Buttons';
$_lang['area_general'] = 'General';
$_lang['area_url'] = 'URL';
$_lang['area_callbacks'] = 'Callbacks';
$_lang['area_layout'] = 'Layout';